config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  #devise_for :users

 

  # resources :users do
  #   collection do
  #     post :webhook
  #   end
  # end

  devise_scope :user do 
    authenticated :user do
      root to: 'clinic/users#home'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root "users#index"
  namespace :clinic do
    resources :users, only: [] do
      collection do
        get :home
      end
    end
    resources :users 
    resources :clients, only: [:index] do
      collection do
        get :home
        get :rehab
        get :change
        get :messages
        get :stats
      end 
    end  

    resources :settings, only: [:create] do
      collection do
        get :dashboard
        get :videos
        get :manage_rewards
        get :abc
      end 
    end  

    resources :accounts , only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

            
 

app/controllers/clinic/accounts_controller.rb
class Clinic::AccountsController < ApplicationController
  def index
  end
end

app/controllers/clinic/clients_controller.rb
class Clinic::ClientsController < ApplicationController
   helper_method :sort_column, :sort_direction

	def index
    if params[:value]
      #@clients = current_user.clients.where(first_name: params[:value]).page(params[:page]).per(params[:limit])
      @clients = current_user.clients.where(first_name: params[:value]).page(params[:page]).per(params[:limit])
    else
      if params[:limit]
       @clients = current_user.clients.page(params[:page]).per(params[:limit])
      else
       @clients = current_user.clients.order("#{sort_column} #{sort_direction}").page(params[:page])

      end
    end
    respond_to do |format|
     format.html
     format.js
    end
	end

  def rehab
  end

  def change
  end

  def messages
  end

  def stats
  end
  private
  def sortable_columns
    ["first_name", "price"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "first_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/clinic/settings_controller.rb
class Clinic::SettingsController < ApplicationController
  
  def dashboard
  end
  
	def manage_rewards
	end

	def videos
		@video  = Video.new
		@video.images.build
	end

	def create
		@video = Video.new(video_params)
		if @video.save!
			@video.images.create(name: params[:video][:images_attributes]["0"]["name"])
			params[:video][:body_locations].each do |b|
        @video.allocations.create(body_location_id: b)
      end  
		end
	end

	def send_for_approve
		@video = Video.find(params[:id])
		status = @video.update(:sending_for_approval) ? true : false
	end

	private
	  def video_params
			params.require(:video).permit(:url, :category, :amount, :type, :sets, :reps, :description, :rehab_name)
		end
end

app/controllers/clinic/users_controller.rb
class Clinic::UsersController < ApplicationController
  
  def home
  	@user = User.new
  end

  def create
  	@user = User.new(client_params)
    @user.check = "client"
    if @user.save
      current_user.members.create(client_id: @user.id)
      add_client_role(@user)
  	  flash[:notice] = "User is successfully created."
  	  redirect_to home_clinic_users_path
    else
  	  render :home
    end
  end

  protected
    

  private
    def client_params
			params.require(:user).permit(:email, :email_confirmation, :first_name, :last_name, :password, :password_confirmation)
		end

    def add_client_role(resource)
      resource.add_role :client
    end
end

app/helpers/clinic/accounts_helper.rb
module Clinic::AccountsHelper
end

app/helpers/clinic/clients_helper.rb
module Clinic::ClientsHelper
	def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/helpers/clinic/settings_helper.rb
module Clinic::SettingsHelper
end

app/helpers/clinic/users_helper.rb
module Clinic::UsersHelper
end

app/views/clinic/clients/_index.html.erb
<div class="table-responsive ac-right">
	<table class="table" cellpadding="0" cellspacing="0">
    <thead>
      <tr>
        <th><%= sort_link "first_name"%>
        	<span class="d-arrow">
        		<img src="/assets/dropdown.png" alt="image">
        	</span>
        </th>
        <th>Active / Inactive
        	<span class="d-arrow">
        		<img src="/assets/dropdown.png" alt="image">
        	</span>
        </th>
        <th>Last Session
        	<span class="d-arrow">
        		<img src="/assets/dropdown.png" alt="image">
        	</span>
        </th>
      </tr>
    </thead>
    <tbody>
      <%@clients.each do |c|%>
        <tr>
          <td class="g-color"><%=link_to "#{c.first_name}", rehab_clinic_clients_path%></td>
          <td class="db-txt">Active</td>
          <td class="db-txt">12/29/2017</td>
        </tr>
      <%end%>
    </tbody>
	</table>
</div>

<%= paginate @clients%>

app/views/clinic/clients/change.html.erb
<!-- db left section -->
<section class="db-sectn">
	<%=render 'layouts/clinic_sidebar'%>
	<%=render 'layouts/clinic_client_sidebar'%>
	<div class="db-mid-3">
		<div class="db-grid">
			<div class="md-block text-center">
				<button class="fullbody-btn">Full Body</button>
			</div>
			<div class="d-flex justify-content-between flex-md-column flex-lg-column flex-xl-row flex-nowrap mt-40 ind-res">
				<div class="align-self-start ind-left">
					<ul class="b-tabs">
						<li class="tab-link an-link1">
							<span>Anterior Neck</span>
						</li>
						<li class="tab-link fc-link2">
							<span>Front Chest</span>
						</li>
						<li class="tab-link fc-link2">
							<span>Biceps</span>
						</li>
						<li class="tab-link hn-link-3">
							<span>Hands/Forearms</span>
						</li>
						<li class="tab-link cr-link-4">
							<span>Core</span>
						</li>
						<li class="tab-link qd-link-5">
							<span>Quadriceps</span>
						</li>
						<li class="tab-link qd-link-5">
							<span>Knee</span>
						</li>
						<li class="tab-link ft-link-6">
							<span>Anterior Tibalis</span>
						</li>
					</ul>
				</div>
				<div class="align-self-start ind-mid">
					<div class="d-flex">
						<div class="mgn-auto fade-body">
							<img src="/assets/body.png" alt="image" class="body">
							<div id="anterior-neck" class="img-hide">
								<div class="an-neck">
									<img src="/assets/body-images/anterior-neck.png" alt="image">
								</div>
							</div>
							<div id="front-chest" class="img-hide">
								<div class="f-chest">
									<img src="/assets/body-images/front-chest.png" alt="image">
								</div>
							</div>
							<div id="front-chest" class="img-hide">
								<div class="f-chest">
									<img src="/assets/body-images/front-chest.png" alt="image">
								</div>
							</div>
							<div id="hand" class="img-hide">
								<div class="h-image">
									<img src="/assets/body-images/hands.png" alt="image">
								</div>
							</div>
							<div id="core" class="img-hide">
								<div class="im-core">
									<img src="/assets/body-images/core.png" alt="image">
								</div>
							</div>
							<div id="quadriceps" class="img-hide">
								<div class="qd-image">
									<img src="/assets/body-images/quadriceps.png" alt="image">
								</div>
							</div>
							<div id="knee" class="img-hide">
								<div class="qd-image">
									<img src="/assets/body-images/quadriceps.png" alt="image">
								</div>
							</div>
							<div id="anterior-tibalis" class="img-hide">
								<div class="feet-img">
									<img src="/assets/body-images/feets.png" alt="image">
								</div>
							</div>
							<div id="posterior-neck" class="img-hide">
								<div class="pn-img">
									<img src="/assets/body-images/posterior-neck.png" alt="image">
								</div>
							</div>
							<div id="upper-back" class="img-hide">
								<div class="up-img">
									<img src="/assets/body-images/upper-back.png" alt="image">
								</div>
							</div>
							<div id="triceps" class="img-hide">
								<div class="up-img">
									<img src="/assets/body-images/upper-back.png" alt="image">
								</div>
							</div>
							<div id="lower-back" class="img-hide">
								<div class="lb-img">
									<img src="/assets/body-images/lower-back.png" alt="image">
								</div>
							</div>
							<div id="glutes" class="img-hide">
								<div class="glu-img">
									<img src="/assets/body-images/hamstrings.png" alt="image">
								</div>
							</div>
							<div id="hamstrings">
								<div class="glu-img">
									<img src="/assets/body-images/hamstrings.png" alt="image">
								</div>
							</div>
							<div id="calves" class="img-hide">
								<div class="feet-img">
									<img src="/assets/body-images/feets.png" alt="image">
								</div>
							</div>
							<div id="feet" class="img-hide">
								<div class="feet-img">
									<img src="/assets/body-images/feets.png" alt="image">
								</div>
							</div>
							<div class="face-front">
								<img src="/assets/body-images/face-front.png" alt="image">
							</div>
							<div class="back-face">
								<img src="/assets/body-images/back-face.png" alt="image">
							</div>
						</div>
					</div>
				</div>
				<div class="align-self-start order-2 ind-right">
					<ul class="b-tabs">
						<li class="tab-link pn-link-8">
							<span>Posterior Neck</span>
						</li>
						<li class="tab-link ft-link-7">
							<span>Upper Back</span>
						</li>
						<li class="tab-link ft-link-7" >
							<span>Triceps</span>
						</li>
						<li class="tab-link lb-link-9" >
							<span>Lower Back</span>
						</li>
						<li class="tab-link gl-link-10" >
							<span>Glutes</span>
						</li>
						<li class="tab-link gl-link-10" >
							<span>Hamstrings</span>
						</li>
						<li class="tab-link ft-link-6" >
							<span>Calves</span>
						</li>
						<li class="tab-link ft-link-6" >
							<span>Feet</span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	
</section>


<!-- jquery -->


<script>
$(document).ready(function(){
	$('.an-link1').click(function(){
		$('#anterior-neck').toggle();
		$('.an-link1 span').toggleClass('color-hover');
	});
	$('.fc-link2').click(function(){
		$('#front-chest').toggle();
		$('.fc-link2 span').toggleClass('color-hover');
	});
	$('.hn-link-3').click(function(){
		$('#hand').toggle();
		$('.hn-link-3 span').toggleClass('color-hover');
	});
	$('.cr-link-4').click(function(){
		$('#core').toggle();
		$('.cr-link-4 span').toggleClass('color-hover');
	});
	$('.qd-link-5').click(function(){
		$('#quadriceps').toggle();
		$('.qd-link-5 span').toggleClass('color-hover');
	});
	$('.ft-link-6').click(function(){
		$('#feet').toggle();
		$('.ft-link-6 span').toggleClass('color-hover');
	});
	$('.ft-link-7').click(function(){
		$('#upper-back').toggle();
		$('.ft-link-7 span').toggleClass('color-hover');
	});
	$('.pn-link-8').click(function(){
		$('#posterior-neck').toggle();
		$('.pn-link-8 span').toggleClass('color-hover');
	});
	$('.lb-link-9').click(function(){
		$('#lower-back').toggle();
		$('.lb-link-9 span').toggleClass('color-hover');
	});
	$('.gl-link-10').click(function(){
		$('#glutes').toggle();
		$('.gl-link-10 span').toggleClass('color-hover');
	});
	$('.fullbody-btn').click(function(){
		$('.img-hide').toggle();
		$('.face-front').toggle();
		$('.back-face').toggle();
		$('.fullbody-btn').toggleClass('color-hover');
		$('.b-tabs li span').toggleClass('color-hover');
	});
	
});
</script>

app/views/clinic/clients/index.html.erb
<section class="db-sectn">
	<%=render 'layouts/clinic_sidebar'%>
	<div class="db-mid-2">
		<div class="db-grid">
			<h3 class="db-headng ovr">
				All Clients
				<div class="pos-right">
					<div class="db-txt in-blck">Show</div>
					<div class="cl-short in-blck">
						<%= form_tag clinic_clients_path, method: :get, id: 'limit_form', remote: true do %>
						  <%= select_tag :limit, options_for_select([5, 10, 15, 20], 
						   selected: params[:limit] || 10) %>
						<% end %>
					</div>
					<div class="db-txt in-blck">Clients</div>
				</div>
			</h3>
			<div id= "posts_list">
			  <%=render partial: 'index',locals: {clients: @clients}%>
			</div>  
			<div class="d-flex justify-content-between">
				<div class="align-self-start">
					<span class="db-txt">
						<!--Showing 1 to 10 Clients of 278 Clients<br>-->
						<%= page_entries_info @clients %>
					</span>
				</div>
			</div>
		</div>
	</div>
</section>


<script>
	$(function(){
		alert("sdf")
	
	});
</script>

app/views/clinic/clients/index.js.erb
<%binding.pry%>

$("#posts_list").html("<%= escape_javascript(render :partial => 'index', :locals =>{:clients => @clients}) %>");

app/views/clinic/clients/messages.html.erb
<!-- db left section -->

<section class="db-sectn">
	<%=render 'layouts/clinic_sidebar'%>
  <%=render 'layouts/clinic_client_sidebar'%>
	<div class="db-mid-3">
		<h3 class="db-headng text-center">JOHN DOE</h3>
		<div class="db-grid">
			<h3 class="db-headng ovr">Messaging</h3>
			<div class="msg-bg tab-width">
				<div class="profile-pic">
					<img src="/assets/profile-pic.jpg" alt="image">
				</div>
				<div class="msg-txt">
					<div class="msg-name">You</div>
					<div class="msg-time">14:00</div>
					<div class="db-txt">
						That's true
					</div>
				</div>
			</div>
			<div class="tab-width p-10">
				<div class="profile-pic">
					<img src="/assets/profile-pic-2.jpg" alt="image">
				</div>
				<div class="msg-txt">
					<div class="msg-name">Jessica Allba</div>
					<div class="msg-time">14:02</div>
					<div class="db-txt">
						That's great! Thank you very much.
					</div>
				</div>
			</div>
			<div class="msg-bg tab-width">
				<div class="profile-pic">
					<img src="/assets/profile-pic.jpg" alt="image">
				</div>
				<div class="msg-txt">
					<div class="msg-name">You</div>
					<div class="msg-time">14:04</div>
					<div class="db-txt">
						It might take 6-10 days to arrive in the UK , if you choose the option .Your package will be fully tracked.
					</div>
				</div>
			</div>
			<div class="tab-width p-10">
				<div class="profile-pic">
					<img src="/assets/profile-pic-2.jpg" alt="image">
				</div>
				<div class="msg-txt">
					<div class="msg-name">Jessica Allba</div>
					<div class="msg-time">14:06</div>
					<div class="db-txt">
						Ok Fine.Do you have those pink sneakers in size 8 ?
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 col-sm-12 form-group">
					<textarea class="form-control form-control-h" rows="2" placeholder="Enter your message here"></textarea>
				</div>
				<div class="col-md-12 col-sm-12">
					<button class="g-btn-auto">
						SEND
					</button>
				</div>
			</div>	
		</div>
	</div>
	
</section>
	


<script>
	$(document).ready(function(){
	    $('#myTable').DataTable();
	});
</script>

app/views/clinic/clients/rehab.html.erb
	<!-- db left section -->

<section class="db-sectn">
  <%=render 'layouts/clinic_sidebar'%>
  <%=render 'layouts/clinic_client_sidebar'%>
	</div>
	<div class="db-mid-3">
		<h3 class="db-headng text-center">JOHN DOE</h3>
		<div class="db-grid">
			<h3 class="db-headng">Stretches</h3>
			<div class="d-flex justify-content-start flex-md-column flex-lg-row flex-xl-row">
				<div class="align-self-center">
					<div class="p-20">
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
					</div>
				</div>
				<div class="align-self-center pl-30 res-pad-20">
					<h3 class="db-heading-2">
						Dumbbell arm lateral raise
					</h3>
					<table class="rahab-list">
						<tbody>
							<tr>
								<td>
									<span class="db-txt">Sets</span>
								</td>
								<td>
									<span class="ca-txt">3 to 6 Steps</span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Reps</span>
								</td>
								<td>
									<span class="ca-txt">3 to 6 Reps</span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Description</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet, </span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Notes to client</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet</span>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="align-self-center ml-auto">
					<button class="trns-btn-2" data-toggle="modal" data-target="#changeStretches">
						<img src="/assets/edit-2.png" alt="image">
						EDIT
					</button>
				</div>
			</div>
			<div class="d-flex justify-content-start mt-20 flex-md-column flex-lg-row flex-xl-row">
				<div class="align-self-center">
					<div class="p-20">
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
					</div>
				</div>
				<div class="align-self-center pl-30 res-pad-20">
					<h3 class="db-heading-2">
						Dumbbell arm lateral raise
					</h3>
					<table class="rahab-list">
						<tbody>
							<tr>
								<td>
									<span class="db-txt">Sets</span>
								</td>
								<td>
									<span class="ca-txt">3 to 6 Steps</span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Reps</span>
								</td>
								<td>
									<span class="ca-txt">3 to 6 Reps</span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Description</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet, </span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Notes to client</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet</span>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="align-self-center ml-auto">
					<button class="trns-btn-2">
						<img src="/assets/edit-2.png" alt="image">
						EDIT
					</button>
				</div>
			</div>
			<div class="seprator"></div>
			<h3 class="db-headng">Exercises</h3>
			<div class="d-flex justify-content-start mt-20 flex-md-column flex-lg-row flex-xl-row">
				<div class="align-self-center">
					<div class="p-20">
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
					</div>
				</div>
				<div class="align-self-center pl-30 res-pad-20">
					<h3 class="db-heading-2">
						Dumbbell arm lateral raise
					</h3>
					<table class="rahab-list">
						<tbody>
							<tr>
								<td>
									<span class="db-txt">Sets</span>
								</td>
								<td>
									<span class="ca-txt">3 to 6 Steps</span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Reps</span>
								</td>
								<td>
									<span class="ca-txt">3 to 6 Reps</span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Description</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet, </span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Notes to client</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet</span>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="align-self-center ml-auto">
					<button class="trns-btn-2">
						<img src="/assets/edit-2.png" alt="image">
						EDIT
					</button>
				</div>
			</div>
			<div class="seprator"></div>
			<h3 class="db-headng">Videos</h3>
			<div class="rehab-v-sectn">
				<ul>
					<li>
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
						<div class="v-captn text-center mt-10">
							<span class="db-txt">Video Name</span>
							<span class="ca-txt md-block">0:00</span>
						</div>
					</li>
					<li>
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
						<div class="v-captn text-center mt-10">
							<span class="db-txt">Video Name</span>
							<span class="ca-txt md-block">0:00</span>
						</div>
					</li>
					<li>
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
						<div class="v-captn text-center mt-10">
							<span class="db-txt">Video Name</span>
							<span class="ca-txt md-block">0:00</span>
						</div>
					</li>
					<li>
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
						<div class="v-captn text-center mt-10">
							<span class="db-txt">Video Name</span>
							<span class="ca-txt md-block">0:00</span>
						</div>
					</li>
					<li>
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
						<div class="v-captn text-center mt-10">
							<span class="db-txt">Video Name</span>
							<span class="ca-txt md-block">0:00</span>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<div class="w-100 text-center mt-20">
			<button class="g-btn-auto" data-toggle="modal" data-target="#sessionComplete">
				SESSION COMPLETED
			</button>
		</div>
	</div>
	
</section>

<!-- edit stretches modal -->

<div class="modal fade" id="changeStretches" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      
        <button type="button" class="close close-ab" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><img src="/assets/close.png" alt="image"></span>
        </button>
      
	    <div class="modal-body">
	        <div class="ch-strtch">
	        	<ul>
	        		<li><span class="db-txt">Change Sets</span></li>
	        		<li>
	        			<select class="form-control">
	        				<option value="">Select(1-8)</option>
	        				<option value="">1</option>
	        				<option value="">2</option>
	        				<option value="">3</option>
	        				<option value="">4</option>
	        				<option value="">5</option>
	        				<option value="">6</option>
	        				<option value="">7</option>
	        				<option value="">8</option>
	        			</select>
	        		</li>
	        	</ul>
	        	<ul>
	        		<li><span class="db-txt">Change Reps</span></li>
	        		<li>
	        			<select class="form-control">
	        				<option value="">Select (3-25)</option>
	        				<option value="">1</option>
	        				<option value="">2</option>
	        				<option value="">3</option>
	        				<option value="">4</option>
	        				<option value="">5</option>
	        				<option value="">6</option>
	        				<option value="">7</option>
	        				<option value="">8</option>
	        				<option value="">9</option>
	        				<option value="">10</option>
	        				<option value="">11</option>
	        				<option value="">12</option>
	        				<option value="">13</option>
	        				<option value="">14</option>
	        				<option value="">15</option>
	        				<option value="">16</option>
	        				<option value="">17</option>
	        				<option value="">18</option>
	        				<option value="">19</option>
	        				<option value="">20</option>
	        				<option value="">21</option>
	        				<option value="">22</option>
	        				<option value="">23</option>
	        				<option value="">24</option>
	        				<option value="">25</option>
	        			</select>
	        		</li>
	        	</ul>
	        	<div class="w-100">
	        		<span class="db-txt">Note to client</span>
	        		<textarea class="form-control form-control-h" rows="3"></textarea>
	        	</div>
	        	<div class="w-100 text-center mt-20">
	        		<button class="g-btn-auto">SAVE</button>
	        	</div>
	        </div>
	    </div>
    </div>
  </div>
</div>

<!-- session complete modal -->

<div class="modal  fade" id="sessionComplete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      
        <button type="button" class="close close-ab" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><img src="/assets/close.png" alt="image"></span>
        </button>
      
	    <div class="modal-body">
	    	<div class="w-100 text-center">
	    		<span class="db-txt">Client session Recorded!</span>
	    	</div>
	    	<div class="w-100 text-center mt-20">
	    		<button class="g-btn-auto mr-10"  data-toggle="modal" data-target="#exampleModal">Print Rehab</button>
	    		<button class="g-btn-auto ml-10">Send Email</button>
	    	</div>
	    </div>
    </div>
  </div>
</div>

<div class="modal sc-modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      
        <button type="button" class="close close-ab" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><img src="/assets/close.png" alt="image"></span>
        </button>
      
	    <div class="modal-body">
	    	<div class="d-flex justify-content-between m-header">
	    		<div class="align-self-center">
	    			<img src="/assets/logo.png" alt="image">
	    		</div>
	    		<div class="align-self-center ml-auto">
	    			<img src="/assets/logo-2.png" alt="image">
	    		</div>
	    	</div>
	    	<div class="ses-date mt-20 text-center">
	    		<span class="ca-txt"><strong>11/10/2017 Sessions</strong></span>
	    	</div>
	        <div class="d-flex justify-content-start mt-20">
				<div class="align-self-center">
					<div class="p-20">
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
					</div>
				</div>
				<div class="align-self-center pl-30 res-pad-20">
					<h3 class="db-heading-2">
						Dumbbell arm lateral raise
					</h3>
					<table class="rahab-list">
						<tbody>
							<tr>
								<td>
									<span class="db-txt">Sets/Reps</span>
								</td>
								<td>
									<span class="ca-txt">3 to 6 Steps</span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Description</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet, </span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Notes to client</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet</span>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class="d-flex justify-content-start mt-20">
				<div class="align-self-center">
					<div class="p-20">
						<div class="avatar">
							<img src="/assets/avatar.png" alt="image">
						</div>
					</div>
				</div>
				<div class="align-self-center pl-30 res-pad-20">
					<h3 class="db-heading-2">
						Dumbbell arm lateral raise
					</h3>
					<table class="rahab-list">
						<tbody>
							<tr>
								<td>
									<span class="db-txt">Sets/Reps</span>
								</td>
								<td>
									<span class="ca-txt">3 to 6 Steps</span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Description</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet, </span>
								</td>
							</tr>
							<tr>
								<td>
									<span class="db-txt">Notes to client</span>
								</td>
								<td>
									<span class="ca-txt">Lorem ipsum dolor sit amet</span>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
	    </div>
    </div>
  </div>
</div>
	