config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  #devise_for :users

 

  # resources :users do
  #   collection do
  #     post :webhook
  #   end
  # end

  devise_scope :user do 
    authenticated :user do
      root to: 'clinic/users#home'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root "users#index"
  namespace :clinic do
    resources :users, only: [] do
      collection do
        get :home
      end
    end
    resources :users 
    resources :clients, only: [:index] do
      collection do
        get :home
        get :rehab
        get :change
        get :messages
        get :stats
      end 
    end  

    resources :settings, only: [:create] do
      collection do
        get :dashboard
        get :videos
        get :manage_rewards
        get :abc
      end 
    end  

    resources :accounts , only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

            
 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  rolify
  attr_accessor :check
  has_many :members, :foreign_key => :clinic_id
  #has_many :members, :foreign_key => :client_id
  has_many :clients, :through => :members, dependent: :destroy
  #has_many :posts, :through => :post_connections, :source => :post_b
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, confirmation: true
  validates :first_name, presence: true, :uniqueness => true,  if: :location_other
  
  def self.search(search, page)
	  paginate :per_page => 5, :page => page,
    :conditions => ['first_name like ?', "%#{search}%"],
    :order => 'name'
	end

  def location_other
    self.check.to_sym == :client if self.check.present?
  end

 

end

app/controllers/clinic/accounts_controller.rb
class Clinic::AccountsController < ApplicationController
  def index
  end
end

app/controllers/clinic/clients_controller.rb
class Clinic::ClientsController < ApplicationController
   helper_method :sort_column, :sort_direction

	def index
    if params[:value]
      #@clients = current_user.clients.where(first_name: params[:value]).page(params[:page]).per(params[:limit])
      @clients = current_user.clients.where(first_name: params[:value]).page(params[:page]).per(params[:limit])
    else
      if params[:limit]
       @clients = current_user.clients.page(params[:page]).per(params[:limit])
      else
       @clients = current_user.clients.order("#{sort_column} #{sort_direction}").page(params[:page])

      end
    end
    respond_to do |format|
     format.html
     format.js
    end
	end

  def rehab
  end

  def change
  end

  def messages
  end

  def stats
  end
  private
  def sortable_columns
    ["first_name", "price"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "first_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/clinic/settings_controller.rb
class Clinic::SettingsController < ApplicationController
  
  def dashboard
  end
  
	def manage_rewards
	end

	def videos
		@video  = Video.new
		@video.images.build
	end

	def create
		@video = Video.new(video_params)
		if @video.save!
			@video.images.create(name: params[:video][:images_attributes]["0"]["name"])
			params[:video][:body_locations].each do |b|
        @video.allocations.create(body_location_id: b)
      end  
		end
	end

	def send_for_approve
		@video = Video.find(params[:id])
		status = @video.update(:sending_for_approval) ? true : false
	end

	private
	  def video_params
			params.require(:video).permit(:url, :category, :amount, :type, :sets, :reps, :description, :rehab_name)
		end
end

app/controllers/clinic/users_controller.rb
class Clinic::UsersController < ApplicationController
  
  def home
  	@user = User.new
  end

  def create
  	@user = User.new(client_params)
    @user.check = "client"
    if @user.save
      current_user.members.create(client_id: @user.id)
      add_client_role(@user)
  	  flash[:notice] = "User is successfully created."
  	  redirect_to home_clinic_users_path
    else
  	  render :home
    end
  end

  protected
    

  private
    def client_params
			params.require(:user).permit(:email, :email_confirmation, :first_name, :last_name, :password, :password_confirmation)
		end

    def add_client_role(resource)
      resource.add_role :client
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	respond_to :html
    after_action :add_clinic_role, only: [:create]

	protected
  	def add_clinic_role
  		resource.add_role :clinic
  	end
end  	

app/helpers/clinic/accounts_helper.rb
module Clinic::AccountsHelper
end

app/helpers/clinic/clients_helper.rb
module Clinic::ClientsHelper
	def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/helpers/clinic/settings_helper.rb
module Clinic::SettingsHelper
end

app/helpers/clinic/users_helper.rb
module Clinic::UsersHelper
end

app/views/clinic/users/home.html.erb
<section class="db-sectn">
	<%=render 'layouts/clinic_sidebar'%>
	<div class="db-mid">
	<%= render 'shared/flash_messages' if !flash.empty? %>

	<%= @user.errors.full_messages.first if @user.errors.any? %>
		<div class="db-grid">
			<ul class="db-list">
				<li class="w-15">
					<span class="db-txt mr-10">Client Name</span>
				</li>
				<li class="w-35">
				<%= form_tag clinic_clients_path, method: :get do %>
				  <%=text_field_tag 'value', "", class: "form_control"%>
				
					</li>
					<li class="w-25 space_between">
						<%=submit_tag "SEARCH", class: "g-btn"%>
					</li>					
			  <%end%>		
				<li class="w-25">
					<button class="b-btn">
						<%=link_to "VIEW ALL CLIENTS", clinic_clients_path%>
					</button>
				</li>
			</ul>
		</div>
		<div class="db-grid mt-20">
			<h3 class="db-headng">
				New Client Entry
			</h3>
			<%= form_for(@user, url: clinic_users_path) do |f| %>
        <%#= devise_error_messages! %>
				<div class="d-flex row">
					<div class="col-sm-12 col-md-12 col-lg-6">
						<div class="form-group">
							<span class="db-txt">First Name</span>
							<%= f.text_field :first_name, class: "form-control" %>
						</div>
					</div> 
					<div class="col-sm-12 col-md-12 col-lg-6">
						<div class="form-group">
							<span class="db-txt">Last Name</span>
							<%= f.text_field :last_name, class: "form-control" %>
						</div>
					</div>
					<div class="col-sm-12 col-md-12 col-lg-6">
						<div class="form-group">
							<span class="db-txt">Email Address</span>
							<%= f.email_field :email, autofocus: true, class: "form-control" %>
						</div>
					</div>
					<div class="col-sm-12 col-md-12 col-lg-6">
						<div class="form-group">
							<span class="db-txt">Re Type Email Address</span>
							<%= f.email_field :email_confirmation, class: "form-control" %>
							<!--<input type="text" class="form-control">-->
						</div>
					</div>
					<div class="col-sm-12 col-md-12 col-lg-6">
						<div class="form-group">
							<span class="db-txt">Password</span>
							<%= f.password_field :password, autocomplete: "off", class: "form-control" %>
						</div>
					</div>
					<div class="col-sm-12 col-md-12 col-lg-6">
						<div class="form-group">
							<span class="db-txt">Re Type Password</span>
							<%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
						</div>
					</div>
					<div class="col-sm-6 col-md-6 col-lg-2">
						<button class="g-btn-auto">
							SUBMIT
						</button>
					</div>
				</div>
		  <%end%>		
		</div>
		<div class="db-grid mt-20">
			<h3 class="db-headng">
				Overall App Usage
			</h3>
			<div class="graph-image">
				<img src="/assets/graph-1.png" alt="image">
			</div>
		</div>
	</div>
	<div class="db-right pull-right">
		<ul>
			<li>
				<img src="/assets/db-icon-right-1.png" alt="image">
				<span class="r-color">5</span>
				<font>Unread Messages</font>
			</li>
			<li>
				<img src="/assets/db-icon-right-2.png" alt="image">
				<span class="y-color">15</span>
				<font>Active Users</font>
			</li>
			<li>
				<img src="/assets/db-icon-right-3.png" alt="image">
				<span class="g2-color">25</span>
				<font>Weekly Clinic Sessions</font>
			</li>
		</ul>
	</div>
</section>
	

app/views/clinic/users/settings.html.erb
<section class="db-sectn">
	<%=render 'layouts/clinic_sidebar'%>
	<%=render 'layouts/setting_sidebar'%>
	<div class="db-mid-3">
		<h3 class="db-headng text-center">JOHN DOE</h3>
		<div class="db-grid">
			<div class="d-flex justify-content-between flex-md-column flex-lg-row flex-xl-row db-tabbls">
				<div class="align-items-start w-40 pr-30 ac-right">
					<h3 class="db-headng ovr">Unread Messages</h3>
					<table cellspacing="0" cellpadding="0">
						<thead>
							<tr>
								<th width="50%">Date</th>
								<th width="50%">Client Name</th>
							</tr>
						</thead>
					</table>
					<div class="mCustomScrollbar scroll-height" data-mcs-theme="inset-3">
						<table class="" cellspacing="0" cellpadding="0">
						<tbody>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">John Smith</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Rose Gold</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Jony Seed</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Tailor Swift</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Jeny Maps</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">John Smith</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Rose Gold</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Jony Seed</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Tailor Swift</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Jeny Maps</td>
							</tr>
						</tbody>
						</table>
					</div>
					<div class="mt-20">
					    <div class="onoffswitch">
					        <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
					        <label class="onoffswitch-label" for="myonoffswitch">
					            <span class="onoffswitch-inner"></span>
					            <span class="onoffswitch-switch"></span>
					        </label>
					    </div>
					</div>
				</div>
				<div class="align-items-start w-60 ac-right">
					<h3 class="db-headng ovr">Redeemed Rewards</h3>
					<table cellspacing="0" cellpadding="0">
						<thead>
							<tr>
								<th width="33.33%">Date</th>
								<th width="33.33%">Client Name</th>
								<th width="33.33%">Reward</th>
							</tr>
						</thead>
					</table>
					<div class="mCustomScrollbar scroll-height" data-mcs-theme="inset-3">
						<table class="" cellspacing="0" cellpadding="0">
						<tbody>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">John Smith</td>
								<td width="33.33%" class="g-color">Bronze Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Rose Gold</td>
								<td width="33.33%" class="g-color">Emrald Gem</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Jonny Seed</td>
								<td width="33.33%" class="g-color">Gold Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Tailor Swift</td>
								<td width="33.33%" class="g-color">Ruby Jam</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Jenny Maps</td>
								<td width="33.33%" class="g-color">Gold Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">John Smith</td>
								<td width="33.33%" class="g-color">Bronze Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Rose Gold</td>
								<td width="33.33%" class="g-color">Emrald Gem</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Jonny Seed</td>
								<td width="33.33%" class="g-color">Gold Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Tailor Swift</td>
								<td width="33.33%" class="g-color">Ruby Jam</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Jonny Seed</td>
								<td width="33.33%" class="g-color">Jenny Maps</td>
							</tr>
						</tbody>
						</table>
					</div>
					<div class="mt-20 d-flex row">
						<div class="col-sm-3 col-lg-3">
							<button class="g-btn">Excel</button>
						</div>
						<div class="col-sm-3 col-lg-3">
							<button class="g-btn">Print</button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<h3 class="db-headng text-center mt-40"><strong>Rehab Portal</strong></h3>
		<div class="cs-ac-tab mt-40">
			<ul class="nav nav-tabs" id="myTab" role="tablist">
			  <li class="nav-item">
			    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true" aria-expanded="true">Stretches</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false" aria-expanded="false">Exercises</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Video</a>
			  </li>
			</ul>
			<div class="tab-content" id="myTabContent">
				<div class="tab-pane  active show" id="home" role="tabpanel" aria-labelledby="home-tab" aria-expanded="true">
			  		<div class="cs-tab-contnt">
			  			<div class="rehab-v-sectn">
							<ul>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							</ul>
						</div>
			  		</div>
			  	</div>
				<div class="tab-pane " id="profile" role="tabpanel" aria-labelledby="profile-tab" aria-expanded="false">
					<div class="cs-tab-contnt">
						Exercises
					</div>
				</div>
				<div class="tab-pane " id="contact" role="tabpanel" aria-labelledby="contact-tab">
					<div class="cs-tab-contnt">
						Video
					</div>
				</div>
			</div>
		</div>
	</div>
	
</section>


<!-- edit video modal -->

<div class="modal fade" id="editVideo" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered add-dash-dialog" role="document">
    <div class="modal-content">
      
        <button type="button" class="close close-ab" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><img src="/assets/close.png" alt="image"></span>
        </button>
      
	    <div class="modal-body">
	    	<div class="d-flex justify-content-start">
	    		<div class="align-items-start w-40 pr-30">
	    			<div class="avatar">
						<img src="/assets/avatar.png" alt="image">
					</div>
					<div class="mt-20 hide-btn">
						<button class="g-btn" type="submit">
							Change Thumbnail
						</button>
						<button class="g-btn mt-10" type="submit">
							Change Video URL
						</button>
						<button class="r-btn mt-10" type="submit">
							Delete Rehab
						</button>
					</div>
	    		</div>
	    		<div class="align-items-start w-60">
			        <div class="ch-strtch db-strtch">
			        	<div class="form-group">
			        		<input type="text" class="form-control" placeholder="Dumbbell arm lateral raise">
			        	</div>
			        	<ul>
			        		<li><span class="db-txt">Sets</span></li>
			        		<li>
			        			<select class="form-control">
			        				<option value="">Select(1-8)</option>
			        				<option value="">1</option>
			        				<option value="">2</option>
			        				<option value="">3</option>
			        				<option value="">4</option>
			        				<option value="">5</option>
			        				<option value="">6</option>
			        				<option value="">7</option>
			        				<option value="">8</option>
			        			</select>
			        		</li>
			        	</ul>
			        	<ul>
			        		<li><span class="db-txt">Reps</span></li>
			        		<li>
			        			<select class="form-control">
			        				<option value="">Select (3-25)</option>
			        				<option value="">1</option>
			        				<option value="">2</option>
			        				<option value="">3</option>
			        				<option value="">4</option>
			        				<option value="">5</option>
			        				<option value="">6</option>
			        				<option value="">7</option>
			        				<option value="">8</option>
			        				<option value="">9</option>
			        				<option value="">10</option>
			        				<option value="">11</option>
			        				<option value="">12</option>
			        				<option value="">13</option>
			        				<option value="">14</option>
			        				<option value="">15</option>
			        				<option value="">16</option>
			        				<option value="">17</option>
			        				<option value="">18</option>
			        				<option value="">19</option>
			        				<option value="">20</option>
			        				<option value="">21</option>
			        				<option value="">22</option>
			        				<option value="">23</option>
			        				<option value="">24</option>
			        				<option value="">25</option>
			        			</select>
			        		</li>
			        	</ul>
			        	<div class="w-100">
			        		<span class="db-txt">Description</span>
			        		<textarea class="form-control form-control-h" rows="3"></textarea>
			        	</div>
			        	<div class="w-100 mt-20">
			        		<div class="d-flex row">
			        			<div class="col-md-4 col-lg-4">
				        			<button class="g-btn change_btn">Change</button>
				        		</div>
				        		<div class="col-md-8 col-lg-8">
				        			<button class="g-btn">Revert back to original</button>
				        		</div>
				        	</div>
			        	</div>
			        </div>
			    </div>
		    </div>
	    </div>
    </div>
  </div>
</div>
<script>
	
</script>

<script>
	$(".change_btn").click(function(){
		$(".hide-btn").addClass("show-btn")
	});
</script>