config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  #devise_for :users

 

  # resources :users do
  #   collection do
  #     post :webhook
  #   end
  # end

  devise_scope :user do 
    authenticated :user do
      root to: 'clinic/users#home'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root "users#index"
  namespace :clinic do
    resources :users, only: [] do
      collection do
        get :home
      end
    end
    resources :users 
    resources :clients, only: [:index] do
      collection do
        get :home
        get :rehab
        get :change
        get :messages
        get :stats
      end 
    end  

    resources :settings, only: [:create] do
      collection do
        get :dashboard
        get :videos
        get :manage_rewards
        get :abc
      end 
    end  

    resources :accounts , only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

            
 

app/controllers/clinic/accounts_controller.rb
class Clinic::AccountsController < ApplicationController
  def index
  end
end

app/controllers/clinic/clients_controller.rb
class Clinic::ClientsController < ApplicationController
   helper_method :sort_column, :sort_direction

	def index
    if params[:value]
      #@clients = current_user.clients.where(first_name: params[:value]).page(params[:page]).per(params[:limit])
      @clients = current_user.clients.where(first_name: params[:value]).page(params[:page]).per(params[:limit])
    else
      if params[:limit]
       @clients = current_user.clients.page(params[:page]).per(params[:limit])
      else
       @clients = current_user.clients.order("#{sort_column} #{sort_direction}").page(params[:page])

      end
    end
    respond_to do |format|
     format.html
     format.js
    end
	end

  def rehab
  end

  def change
  end

  def messages
  end

  def stats
  end
  private
  def sortable_columns
    ["first_name", "price"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "first_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/clinic/settings_controller.rb
class Clinic::SettingsController < ApplicationController
  
  def dashboard
  end
  
	def manage_rewards
	end

	def videos
		@video  = Video.new
		@video.images.build
	end

	def create
		@video = Video.new(video_params)
		if @video.save!
			@video.images.create(name: params[:video][:images_attributes]["0"]["name"])
			params[:video][:body_locations].each do |b|
        @video.allocations.create(body_location_id: b)
      end  
		end
	end

	def send_for_approve
		@video = Video.find(params[:id])
		status = @video.update(:sending_for_approval) ? true : false
	end

	private
	  def video_params
			params.require(:video).permit(:url, :category, :amount, :type, :sets, :reps, :description, :rehab_name)
		end
end

app/controllers/clinic/users_controller.rb
class Clinic::UsersController < ApplicationController
  
  def home
  	@user = User.new
  end

  def create
  	@user = User.new(client_params)
    @user.check = "client"
    if @user.save
      current_user.members.create(client_id: @user.id)
      add_client_role(@user)
  	  flash[:notice] = "User is successfully created."
  	  redirect_to home_clinic_users_path
    else
  	  render :home
    end
  end

  protected
    

  private
    def client_params
			params.require(:user).permit(:email, :email_confirmation, :first_name, :last_name, :password, :password_confirmation)
		end

    def add_client_role(resource)
      resource.add_role :client
    end
end

app/helpers/clinic/accounts_helper.rb
module Clinic::AccountsHelper
end

app/helpers/clinic/clients_helper.rb
module Clinic::ClientsHelper
	def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/helpers/clinic/settings_helper.rb
module Clinic::SettingsHelper
end

app/helpers/clinic/users_helper.rb
module Clinic::UsersHelper
end

app/views/clinic/settings/_success_video_modal.html.erb
<%binding.pry%>
<div class="modal  fade" id="addVideo" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered add-vid-dialog" role="document">
	    <div class="modal-content">
	      
	        <button type="button" class="close close-ab" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true"><img src="/assets/close.png" alt="image"></span>
	        </button>
	      
		    <div class="modal-body">
		    	<div class="approv-img text-center">
		    		<img src="/assets/approv.png" alt="image">
		    	</div>
		    	<div class="mt-20 text-center">
		    		<span class="g-color">
		    			Congrats, your clinic video has been added!
		    		</span>
		    	</div>
		    	<div class="mt-10 text-center">
		    		<span class="db-txt">
		    			Would you like to submit this for approval to the community videos, or keep for your internal clinic use only?
		    		</span>
		    	</div>
		    	<div class="mt-20">
		    		<div class="row d-flex">
		    			<div class="col-md-6 col-lg-6">
		    				<button class="g-btn-auto" type="submit">
		    					Yes, Please Submit for Approval 
		    				</button>
		    			</div>
		    			<div class="col-md-6 col-lg-6">
		    				<button class="r-btn-auto" type="submit">
		    					No Thanks, Please keep internal
		    				</button>
		    			</div>
		    		</div>
		    	</div>
		    </div>
	    </div>
	  </div>
	</div>

app/views/clinic/settings/create.js.erb
<%binding.pry%>

$("#video_popup").html("<%= escape_javascript(render :partial => 'success_video_modal', :locals =>{:video_id => @video.id}) %>");
$('#addVideo').modal('show');

app/views/clinic/settings/dashboard.html.erb
<!-- db left section -->

<section class="db-sectn">
	<%=render 'layouts/clinic_sidebar'%>
	<%=render 'layouts/setting_sidebar'%>
	<div class="db-mid-3">
		<h3 class="db-headng text-center">JOHN DOE</h3>
		<div class="db-grid">
			<div class="d-flex justify-content-between flex-md-column flex-lg-row flex-xl-row db-tabbls">
				<div class="align-items-start w-40 pr-30 ac-right">
					<h3 class="db-headng ovr">Unread Messages</h3>
					<table cellspacing="0" cellpadding="0">
						<thead>
							<tr>
								<th width="50%">Date</th>
								<th width="50%">Client Name</th>
							</tr>
						</thead>
					</table>
					<div class="mCustomScrollbar scroll-height" data-mcs-theme="inset-3">
						<table class="" cellspacing="0" cellpadding="0">
						<tbody>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">John Smith</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Rose Gold</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Jony Seed</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Tailor Swift</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Jeny Maps</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">John Smith</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Rose Gold</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Jony Seed</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Tailor Swift</td>
							</tr>
							<tr>
								<td width="50%" class="db-txt">11/10/2017</td>
								<td width="50%" class="g-color">Jeny Maps</td>
							</tr>
						</tbody>
						</table>
					</div>
					<div class="mt-20">
					    <div class="onoffswitch">
					        <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
					        <label class="onoffswitch-label" for="myonoffswitch">
					            <span class="onoffswitch-inner"></span>
					            <span class="onoffswitch-switch"></span>
					        </label>
					    </div>
					</div>
				</div>
				<div class="align-items-start w-60 ac-right">
					<h3 class="db-headng ovr">Redeemed Rewards</h3>
					<table cellspacing="0" cellpadding="0">
						<thead>
							<tr>
								<th width="33.33%">Date</th>
								<th width="33.33%">Client Name</th>
								<th width="33.33%">Reward</th>
							</tr>
						</thead>
					</table>
					<div class="mCustomScrollbar scroll-height" data-mcs-theme="inset-3">
						<table class="" cellspacing="0" cellpadding="0">
						<tbody>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">John Smith</td>
								<td width="33.33%" class="g-color">Bronze Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Rose Gold</td>
								<td width="33.33%" class="g-color">Emrald Gem</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Jonny Seed</td>
								<td width="33.33%" class="g-color">Gold Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Tailor Swift</td>
								<td width="33.33%" class="g-color">Ruby Jam</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Jenny Maps</td>
								<td width="33.33%" class="g-color">Gold Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">John Smith</td>
								<td width="33.33%" class="g-color">Bronze Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Rose Gold</td>
								<td width="33.33%" class="g-color">Emrald Gem</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Jonny Seed</td>
								<td width="33.33%" class="g-color">Gold Star</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Tailor Swift</td>
								<td width="33.33%" class="g-color">Ruby Jam</td>
							</tr>
							<tr>
								<td width="33.33%" class="db-txt">11/10/2017</td>
								<td width="33.33%" class="g-color">Jonny Seed</td>
								<td width="33.33%" class="g-color">Jenny Maps</td>
							</tr>
						</tbody>
						</table>
					</div>
					<div class="mt-20 d-flex row">
						<div class="col-sm-3 col-lg-3">
							<button class="g-btn">Excel</button>
						</div>
						<div class="col-sm-3 col-lg-3">
							<button class="g-btn">Print</button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<h3 class="db-headng text-center mt-40"><strong>Rehab Portal</strong></h3>
		<div class="cs-ac-tab mt-40">
			<ul class="nav nav-tabs" id="myTab" role="tablist">
			  <li class="nav-item">
			    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true" aria-expanded="true">Stretches</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false" aria-expanded="false">Exercises</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Video</a>
			  </li>
			</ul>
			<div class="tab-content" id="myTabContent">
				<div class="tab-pane  active show" id="home" role="tabpanel" aria-labelledby="home-tab" aria-expanded="true">
			  		<div class="cs-tab-contnt">
			  			<div class="rehab-v-sectn">
							<ul>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							<li>
								<div class="avatar">
									<img src="/assets/avatar.png" alt="image">
								</div>
								<div class="v-captn text-center mt-10">
									<span class="db-txt">Dumbbell arm lateral raise</span>
									<span class="md-block mt-10">
										<button class="trns-btn-2" data-toggle="modal" data-target="#editVideo">
											<img src="/assets/edit-2.png" alt="image">
											EDIT
										</button>
									</span>
								</div>
							</li>
							</ul>
						</div>
			  		</div>
			  	</div>
				<div class="tab-pane " id="profile" role="tabpanel" aria-labelledby="profile-tab" aria-expanded="false">
					<div class="cs-tab-contnt">
						Exercises
					</div>
				</div>
				<div class="tab-pane " id="contact" role="tabpanel" aria-labelledby="contact-tab">
					<div class="cs-tab-contnt">
						Video
					</div>
				</div>
			</div>
		</div>
	</div>
	
</section>


<!-- edit video modal -->

<div class="modal fade" id="editVideo" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered add-dash-dialog" role="document">
    <div class="modal-content">
      
        <button type="button" class="close close-ab" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><img src="/assets/close.png" alt="image"></span>
        </button>
      
	    <div class="modal-body">
	    	<div class="d-flex justify-content-start">
	    		<div class="align-items-start w-40 pr-30">
	    			<div class="avatar">
						<img src="/assets/avatar.png" alt="image">
					</div>
					<div class="mt-20 hide-btn">
						<button class="g-btn" type="submit">
							Change Thumbnail
						</button>
						<button class="g-btn mt-10" type="submit">
							Change Video URL
						</button>
						<button class="r-btn mt-10" type="submit">
							Delete Rehab
						</button>
					</div>
	    		</div>
	    		<div class="align-items-start w-60">
			        <div class="ch-strtch db-strtch">
			        	<div class="form-group">
			        		<input type="text" class="form-control" placeholder="Dumbbell arm lateral raise">
			        	</div>
			        	<ul>
			        		<li><span class="db-txt">Sets</span></li>
			        		<li>
			        			<select class="form-control">
			        				<option value="">Select(1-8)</option>
			        				<option value="">1</option>
			        				<option value="">2</option>
			        				<option value="">3</option>
			        				<option value="">4</option>
			        				<option value="">5</option>
			        				<option value="">6</option>
			        				<option value="">7</option>
			        				<option value="">8</option>
			        			</select>
			        		</li>
			        	</ul>
			        	<ul>
			        		<li><span class="db-txt">Reps</span></li>
			        		<li>
			        			<select class="form-control">
			        				<option value="">Select (3-25)</option>
			        				<option value="">1</option>
			        				<option value="">2</option>
			        				<option value="">3</option>
			        				<option value="">4</option>
			        				<option value="">5</option>
			        				<option value="">6</option>
			        				<option value="">7</option>
			        				<option value="">8</option>
			        				<option value="">9</option>
			        				<option value="">10</option>
			        				<option value="">11</option>
			        				<option value="">12</option>
			        				<option value="">13</option>
			        				<option value="">14</option>
			        				<option value="">15</option>
			        				<option value="">16</option>
			        				<option value="">17</option>
			        				<option value="">18</option>
			        				<option value="">19</option>
			        				<option value="">20</option>
			        				<option value="">21</option>
			        				<option value="">22</option>
			        				<option value="">23</option>
			        				<option value="">24</option>
			        				<option value="">25</option>
			        			</select>
			        		</li>
			        	</ul>
			        	<div class="w-100">
			        		<span class="db-txt">Description</span>
			        		<textarea class="form-control form-control-h" rows="3"></textarea>
			        	</div>
			        	<div class="w-100 mt-20">
			        		<div class="d-flex row">
			        			<div class="col-md-4 col-lg-4">
				        			<button class="g-btn change_btn">Change</button>
				        		</div>
				        		<div class="col-md-8 col-lg-8">
				        			<button class="g-btn">Revert back to original</button>
				        		</div>
				        	</div>
			        	</div>
			        </div>
			    </div>
		    </div>
	    </div>
    </div>
  </div>
</div>

app/views/clinic/settings/manage_rewards.html.erb
	<!-- db left section -->

	<section class="db-sectn">
		<%=render 'layouts/clinic_sidebar'%>
		<%=render 'layouts/setting_sidebar'%>
		<div class="db-mid-3">
			<h3 class="db-headng text-center">JOHN DOE</h3>
			<div class="db-grid">
				<h3 class="db-headng ovr">Manage Rewards</h3>
				<span class="db-txt">
					Replace a virtual game reward with a real clinic offering such as 100% off product, etc. Each reward takes 100 app points (minutes) to achieve. 
				</span>
				<div class="row d-flex mt-20">
					<div class="col-md-12 col-lg-12 col-xl-6 ac-right">
						<table class="" cellspacing="0" cellpadding="0">
							<thead>
								<tr>
									<th>Standard Reward</th>
									<th>Clinic Reward</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td class="db-txt">Emerald Gem</td>
									<td class="">
										<a href="#" class="g-color" data-toggle="modal" data-target="#replaceGem">Replace</a>
									</td>
								</tr>
								<tr>
									<td class="db-txt">Sapphire Gem</td>
									<td class="">
										<a href="#" class="g-color" data-toggle="modal" data-target="#replaceGem">Replace</a>
									</td>
								</tr>
								<tr>
									<td class="db-txt">Ruby Gem</td>
									<td class="">
										<a href="#" class="g-color" data-toggle="modal" data-target="#replaceGem">Replace</a>
									</td>
								</tr>
								<tr>
									<td class="db-txt">Diamond Gem</td>
									<td class="">
										<a href="#" class="g-color" data-toggle="modal" data-target="#replaceGem">Replace</a>
									</td>
								</tr>
								<tr>
									<td class="db-txt">Bronze Star</td>
									<td class="">
										<a href="#" class="g-color" data-toggle="modal" data-target="#replaceGem">Replace</a>
									</td>
								</tr>
								<tr>
									<td class="db-txt">Silver Star</td>
									<td class="">
										<a href="#" class="g-color" data-toggle="modal" data-target="#replaceGem">Replace</a>
									</td>
								</tr>
								<tr>
									<td class="db-txt">Gold Star</td>
									<td class="">
										<a href="#" class="g-color" data-toggle="modal" data-target="#replaceGem">Replace</a>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="mt-10 md-block">
					<div class="db-txt">
						<small>
							*Note any changes will also change on Client's Mobile App, in effect from the moment forward office discretion to reward former earners prior to clinic reward changes taking place
						</small>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Replace Gem modal -->

	<div class="modal fade" id="replaceGem" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered add-dash-dialog" role="document">
	    <div class="modal-content">
	      
	        <button type="button" class="close close-ab" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true"><img src="images/close.png" alt="image"></span>
	        </button>
	      
		    <div class="modal-body">
		    	<span class="md-block db-txt">Replace Diamond Gem with</span>
		    	<select class="form-control">
		    		<option value="">10% OFF Product</option>
		    		<option value="">10% OFF Product</option>
		    		<option value="">10% OFF Product</option>
		    		<option value="">10% OFF Product</option>
		    	</select>
		    	<div class="mt-20 text-center">
			    	<div class="db-txt">
						<small>
							*Note any changes will also change on Client's Mobile App, in effect from the moment forward office discretion to reward former earners prior to clinic reward changes taking place
						</small>
					</div>
		    	</div>
		    	<div class="mt-20 text-center">
			    	<button class="g-btn-auto" type="submit">
			    		Change
			    	</button>
		    	</div>
		    </div>
		    
		    
	    </div>
	  </div>
	</div>


	

	
	


<script>
	$(".change_btn").click(function(){
		$(".hide-btn").addClass("show-btn")
	});
</script>

app/views/clinic/settings/send_for_approve.js.erb
<%if @status%>
  $('#abc').fadeOut();
<%end%>

app/views/clinic/settings/videos.html.erb
	<section class="db-sectn">
		<%=render 'layouts/clinic_sidebar'%>
		<%=render 'layouts/setting_sidebar'%>
		<div class="db-mid-3">
			<h3 class="db-headng text-center">JOHN DOE</h3>
		<%=form_for @video, :url => clinic_settings_path,  method: :post, remote: true do |f|%>
			<div class="db-grid">
				<h3 class="db-headng ovr">Add Own Videos</h3>
				<div class="d-flex justify-content-start flex-md-column flex-lg-row flex-xl-row add-v-sec">
					<div class="align-self-start pr-30 w-25">
						<button class="trns-btn-2">ADD THUMBNAIL</button>
						<%= f.fields_for :images do |builder| %>
						  <%# if builder.object.new_record? %>
                          <%= link_to "javascript:;" , class: "browseBtn" do %>
					      <%= builder.file_field :name%>
					  <% end %>
              <%# end %>
				    <% end %>
				          
						<div class="avatar mt-20">
							<img src="/assets/avatar.png" alt="image">
						</div>
					</div>
					<div class="align-self-start pr-30 w-40">
						<div class="db-txt">Add Video</div>
						<div class="mt-10 av-inp">
							<span class="db-txt f_contrl">www.youtube.com/</span>
							<%= f.text_field :url, class: "form-control" %>
						</div>
						<div class="form-group mt-10">
							<span class="db-txt">Point Amount</span>
						  <%= f.select :amount, ['select', 'Lorem Ipsum', 'Lorem Ipsum'], {},{class: "form-control"}%>
						</div>

						<div class="db-txt">Type</div>
							<div class="radio-list mt-10">
								<ul>
									<li>
									 	<div class="radio">
			  								<label class="radioType db-txt">Stretch
											 
											  <%= f.radio_button :type, :stretch, :checked => true%>

											  <span class="checkmark"></span>
											</label>
										</div>
									</li>
									<li>
										<div class="radio">
										    <label class="radioType db-txt">Exercise
											  <%= f.radio_button :type, :exercise %>
											  <span class="checkmark"></span>
										    </label>
										</div>
									</li>
									<li>
										<div class="radio">
										    <label class="radioType db-txt">Video
											  <%= f.radio_button :type, :video %>
											  <span class="checkmark"></span>
										    </label>
										</div>
									</li>
								</ul>
							</div>
						</div>
					<div class="align-self-start w-35">
						<div class="form-group">
							<span class="db-txt">Rehab Name</span>
							<%= f.text_field :rehab_name, class: "form-control" %>
						</div>
						<div class="form-group">
							<span class="db-txt">Sets</span>
							<%= f.select :sets, ['select', 'Lorem Ipsum', 'Lorem Ipsum'], {},{class: "form-control"}%>
						</div>
						<div class="form-group">
							<span class="db-txt">Reps</span>
							<%= f.select :reps, ['select', 'Lorem Ipsum', 'Lorem Ipsum'], {},{class: "form-control"}%>
						</div>
						<div>
							<span class="db-txt">Description</span>
							<textarea class="form-control form-control-h" rows="1" placeholder="Raise arm slightly overhead, be sure to write anything else you want to here." name="video[description]"></textarea>
						</div>
					</div>
				</div>
				<div class="mt-20">
					<div class="db-headng">Body Locations</div>
					<ul class="av-vid-list">
					  <%BodyLocation.all.each.with_index(1) do |b, index|%>
					    <%if index % 5 == 0%>
					      </ul>
					      <ul class="av-vid-list">
					    <%end%>
					    <%ch  = (index == 1) ? "true" : "" %>
							<li>
								<label class="checkboxType db-txt"><%=b.name%>
								  <input type="checkbox" value = "<%=b.id%>" checked="false" name="video[body_locations][]">
								  <span class="checkmark"></span>
								</label>

							</li>
						<%end%>					
				</div>
				<div class="mt-20">
					<button class="g-btn-auto" data-toggle="modal">
						SUBMIT
					</button>
				</div>
			</div>
		</div>
		<%end%>
		
	</section>


	<!-- video added modal -->

	<div class="modal  fade" id="addVideo" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered add-vid-dialog" role="document">
	    <div class="modal-content">
	      
	        <button type="button" class="close close-ab" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true"><img src="/assets/close.png" alt="image"></span>
	        </button>
	      
		    <div class="modal-body">
		    	<div class="approv-img text-center">
		    		<img src="/assets/approv.png" alt="image">
		    	</div>
		    	<div class="mt-20 text-center">
		    		<span class="g-color">
		    			Congrats, your clinic video has been added!
		    		</span>
		    	</div>
		    	<div class="mt-10 text-center">
		    		<span class="db-txt">
		    			Would you like to submit this for approval to the community videos, or keep for your internal clinic use only?
		    		</span>
		    	</div>
		    	<div class="mt-20">
		    		<div class="row d-flex">
		    			<div class="col-md-6 col-lg-6">
		    				<button class="g-btn-auto" type="submit">
		    					Yes, Please Submit for Approval 
		    				</button>
		    			</div>
		    			<div class="col-md-6 col-lg-6">
		    				<button class="r-btn-auto" type="submit">
		    					No Thanks, Please keep internal
		    				</button>
		    			</div>
		    		</div>
		    	</div>
		    </div>
	    </div>
	  </div>
	</div>